export const CUISINES = [
  "Indian",
  "North Indian",
  "South Indian",
  "Punjabi",
  "Rajasthani",
  "Gujarati",
  "Bengali",
  "Maharashtrian",
  "Kerala",
  "Hyderabadi",
  "Kashmiri",
  "Chinese",
  "Indo-Chinese",
  "Thai",
  "Japanese",
  "Korean",
  "Vietnamese",
  "Asian",
  "Italian",
  "French",
  "Spanish",
  "Greek",
  "Mediterranean",
  "Mexican",
  "American",
  "Tex-Mex",
  "Middle Eastern",
  "Turkish",
  "Lebanese",
  "Arabian",
  "Persian",
  "Fast Food",
  "Street Food",
  "Cafe",
  "Bakery",
  "Desserts",
  "Ice Cream",
  "BBQ",
  "Grill",
  "Seafood",
  "Steakhouse",
  "Healthy",
  "Salads",
  "Organic",
  "Vegan",
  "Vegetarian",
  "Fusion",
  "Continental"
] as const;


export const RESTAURANT_TAGS = [
  "family-friendly",
  "romantic",
  "fine-dining",
  "casual-dining",
  "quick-bites",
  "buffet",
  "all-you-can-eat",
  "rooftop",
  "outdoor-seating",
  "indoor-seating",
  "live-music",
  "live-sports",
  "pet-friendly",
  "kids-friendly",
  "wifi",
  "parking",
  "valet-parking",
  "wheelchair-accessible",
  "smoking-area",
  "non-smoking",
  "open-late",
  "24-hours",
  "takeaway",
  "delivery",
  "drive-thru",
  "reservations",
  "private-dining",
  "group-friendly",
  "date-night",
  "business-meeting",
  "birthday-party",
  "anniversary",
  "good-for-lunch",
  "good-for-dinner",
  "good-for-breakfast",
  "good-for-brunch",
  "instagrammable",
  "luxury",
  "budget-friendly"
] as const;

export const DAYS = [
  "mon",
  "tue",
  "wed",
  "thu",
  "fri",
  "sat",
  "sun"
] as const

export type Day = typeof DAYS[number]
export type RestaurantTagType = typeof RESTAURANT_TAGS[number];
export type CuisineType = typeof CUISINES[number];
